name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Go mod download
      run: go mod download

    - name: Run go build
      run: go build ./...

    - name: Build docker image (local validation)
      uses: docker/build-push-action@v5
      with:
        push: false
        platforms: linux/amd64,linux/arm64
        tags: hermyx:ci
        file: Dockerfile
